### ISSUE TITLE
Rename this repo to use dashes

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-sagan#77]
When I first created this repo, I named it with dots because that's how it's represented in Python, but the convention appears to be dashes and all other RIPE projects use dashes, so it would be nice to make this one conform.

I understand that GitHub retains a redirect for old names so old checkouts should still work (at least that's been my experience) so why not rename it?

**Comment by chrisamin** [comment]
Seems to work!
