### ISSUE TITLE
No tarball available at PyPI

### ISSUE THREAD

**Issue by nunotexbsd** [RIPE-NCC/ripe-atlas-sagan#95]
There will be plans to add src tarballs related to ripe.atlas{cousteau,sagan,tools} to PyPI?

For example, ripe.atlas.tools 3.1.0: https://pypi.org/project/ripe.atlas.tools/3.1.0/#files

Thanks

**Comment by chrisamin** [comment]
Hi, 

Would you mind letting us know your use case for uploading sdist packages for these tools?

**Comment by stucchimax** [comment]
This specific case is for FreeBSD Ports/packages.  Ultimately, for just using pip...

**Comment by nunotexbsd** [comment]
Yes, right.

Almost all FreeBSD python ports get tarballs from PyPI.
There we find a fixed tarball and not a auto-generated one like in github (for exception for projects that provide one).
 
More on tarballs:

_As of 2023-02-21 [GitHub](https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/) have announced that source downloads will be stable for a year. Please switch to release assets and if not available ask upstream to generate ones._

**Comment by chrisamin** [comment]
Okay, I've uploaded sdists for ripe.atlas{cousteau,sagan,tools} for the latest versions (note new 3.1.1 patch version for tools)

**Comment by nunotexbsd** [comment]
@chrisamin

Thank you very much.
